package com.example.envmonitor.service;

import com.example.envmonitor.dto.SensorDataRequest;
import com.example.envmonitor.entity.SensorData;
import com.example.envmonitor.repository.SensorDataRepository;
import com.example.envmonitor.util.DataSourceUtils;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

@Service
public class SensorDataService {
    public static final String SOURCE_REAL_SERIAL = DataSourceUtils.REAL_SERIAL;
    public static final String SOURCE_REAL_MQTT = DataSourceUtils.REAL_MQTT;
    public static final String SOURCE_MOCK = DataSourceUtils.MOCK;
    public static final String SOURCE_MANUAL = DataSourceUtils.MANUAL;
    public static final String SOURCE_ALL = DataSourceUtils.ALL;

    private static final double GAS_WARNING_THRESHOLD = 50.0;
    private static final double TEMPERATURE_WARNING_THRESHOLD = 40.0;
    private static final double HUMIDITY_WARNING_THRESHOLD = 80.0;
    private static final Pattern KEY_VALUE_PATTERN = Pattern.compile("([a-zA-Z_][a-zA-Z0-9_]*)\\s*=\\s*([^,]+)");
    private static final Pattern NUMBER_PREFIX_PATTERN = Pattern.compile("[-+]?[0-9]*\\.?[0-9]+");

    private final SensorDataRepository repository;
    private final ObjectMapper objectMapper;
    private final CacheInvalidationService cacheInvalidationService;
    private final Random random = new Random();

    public SensorDataService(
        SensorDataRepository repository,
        ObjectMapper objectMapper,
        CacheInvalidationService cacheInvalidationService
    ) {
        this.repository = repository;
        this.objectMapper = objectMapper;
        this.cacheInvalidationService = cacheInvalidationService;
    }

    @Transactional
    public SensorData create(SensorDataRequest request) {
        validateRequest(request);
        SensorData data = new SensorData();
        data.setDeviceId(StringUtils.hasText(request.getDeviceId()) ? request.getDeviceId() : "Hi3861-DeviceA");
        data.setTemperature(round1(request.getTemperature()));
        data.setHumidity(round1(request.getHumidity()));
        data.setGas(round1(request.getGas()));
        data.setStatus(judgeStatus(data.getTemperature(), data.getHumidity(), data.getGas()));
        data.setDataSource(DataSourceUtils.normalizeWriteSource(request.getDataSource()));
        data.setRawMessage(request.getRawMessage());
        data.setCreatedAt(LocalDateTime.now());
        SensorData saved = repository.save(data);
        cacheInvalidationService.clearAllDataCaches();
        return saved;
    }

    @Transactional
    public Optional<SensorData> createFromMqttMessage(String payload) {
        try {
            SensorDataRequest request = parsePayload(payload);
            request.setDataSource(SOURCE_REAL_MQTT);
            request.setRawMessage(payload);
            return Optional.of(create(request));
        } catch (RuntimeException ex) {
            System.out.println("[MQTT] Ignore invalid payload: " + payload + ", reason=" + ex.getMessage());
            return Optional.empty();
        }
    }

    @Transactional
    public SensorData createMockData() {
        SensorDataRequest request = new SensorDataRequest();
        request.setDeviceId("Hi3861-DeviceA");
        request.setTemperature(round1(25.0 + random.nextDouble() * 8.0));
        request.setHumidity(round1(35.0 + random.nextDouble() * 35.0));
        request.setGas(round1(15.0 + random.nextDouble() * 55.0));
        request.setDataSource(SOURCE_MOCK);
        request.setRawMessage("manual mock data generated by POST /api/sensor-data/mock");
        return create(request);
    }

    @Transactional(readOnly = true)
    public Optional<SensorData> latest() {
        return repository.findTopByOrderByCreatedAtDesc();
    }

    @Transactional(readOnly = true)
    @Cacheable(cacheNames = "latestSensorDataCache", key = "#source")
    public Optional<SensorData> latestBySource(String source) {
        String dataSource = normalizeSource(source);
        if (SOURCE_ALL.equals(dataSource)) {
            return repository.findTopByOrderByCreatedAtDesc();
        }
        return repository.findTopByDataSourceOrderByCreatedAtDesc(dataSource);
    }

    @Transactional(readOnly = true)
    public List<SensorData> recent(int limit) {
        int boundedLimit = boundLimit(limit);
        return repository.findAllByOrderByCreatedAtDesc(PageRequest.of(0, boundedLimit));
    }

    @Transactional(readOnly = true)
    @Cacheable(cacheNames = "recentSensorDataCache", key = "#source + '_' + #limit")
    public List<SensorData> recentBySource(String source, int limit) {
        int boundedLimit = boundLimit(limit);
        String dataSource = normalizeSource(source);
        if (SOURCE_ALL.equals(dataSource)) {
            return repository.findAllByOrderByCreatedAtDesc(PageRequest.of(0, boundedLimit));
        }
        return repository.findByDataSourceOrderByCreatedAtDesc(dataSource, PageRequest.of(0, boundedLimit));
    }

    @Transactional(readOnly = true)
    public List<SensorData> all() {
        return repository.findAll().stream()
            .sorted(Comparator.comparing(SensorData::getCreatedAt).reversed())
            .toList();
    }

    @Transactional(readOnly = true)
    public List<SensorData> allBySource(String source) {
        String dataSource = normalizeSource(source);
        if (SOURCE_ALL.equals(dataSource)) {
            return all();
        }
        return repository.findByDataSourceOrderByCreatedAtDesc(dataSource);
    }

    @Transactional(readOnly = true)
    public List<SensorData> warnings() {
        return repository.findByStatusOrderByCreatedAtDesc("WARNING");
    }

    @Transactional(readOnly = true)
    public List<SensorData> warningsBySource(String source) {
        String dataSource = normalizeSource(source);
        if (SOURCE_ALL.equals(dataSource)) {
            return warnings();
        }
        return repository.findByStatusAndDataSourceOrderByCreatedAtDesc("WARNING", dataSource);
    }

    public String judgeStatus(double temperature, double humidity, double gas) {
        if (gas >= GAS_WARNING_THRESHOLD || temperature >= TEMPERATURE_WARNING_THRESHOLD || humidity >= HUMIDITY_WARNING_THRESHOLD) {
            return "WARNING";
        }
        return "SAFE";
    }

    public String normalizeSource(String source) {
        return DataSourceUtils.normalizeQuerySource(source);
    }

    private SensorDataRequest parsePayload(String payload) {
        if (!StringUtils.hasText(payload)) {
            throw new IllegalArgumentException("empty payload");
        }
        String trimmed = payload.trim();
        if (trimmed.startsWith("{")) {
            return parseJsonPayload(trimmed);
        }
        return parseKeyValuePayload(trimmed);
    }

    private SensorDataRequest parseJsonPayload(String payload) {
        try {
            JsonNode node = objectMapper.readTree(payload);
            SensorDataRequest request = new SensorDataRequest();
            request.setDeviceId(node.path("deviceId").asText("Hi3861-DeviceA"));
            request.setTemperature(requiredDouble(node, "temperature"));
            request.setHumidity(requiredDouble(node, "humidity"));
            request.setGas(requiredDouble(node, "gas"));
            request.setStatus(node.path("status").asText(null));
            request.setDataSource(node.path("dataSource").asText(null));
            request.setRawMessage(node.path("rawMessage").asText(null));
            return request;
        } catch (Exception ex) {
            throw new IllegalArgumentException("invalid json payload", ex);
        }
    }

    private SensorDataRequest parseKeyValuePayload(String payload) {
        SensorDataRequest request = new SensorDataRequest();
        request.setDeviceId("Hi3861-DeviceA");
        Matcher matcher = KEY_VALUE_PATTERN.matcher(payload);
        while (matcher.find()) {
            String key = matcher.group(1).toLowerCase(Locale.ROOT);
            String value = matcher.group(2).trim();
            if ("deviceid".equals(key) || "device_id".equals(key)) {
                request.setDeviceId(value);
            } else if ("temperature".equals(key) || "temp".equals(key)) {
                request.setTemperature(parseNumber(value));
            } else if ("humidity".equals(key) || "hum".equals(key)) {
                request.setHumidity(parseNumber(value));
            } else if ("gas".equals(key)) {
                request.setGas(parseNumber(value));
            } else if ("status".equals(key)) {
                request.setStatus(value.toUpperCase(Locale.ROOT));
            } else if ("datasource".equals(key) || "data_source".equals(key)) {
                request.setDataSource(value);
            }
        }
        validateRequest(request);
        return request;
    }

    private Double requiredDouble(JsonNode node, String fieldName) {
        if (!node.has(fieldName)) {
            throw new IllegalArgumentException("missing numeric field: " + fieldName);
        }
        JsonNode value = node.get(fieldName);
        if (value.isNumber()) {
            return value.asDouble();
        }
        if (value.isTextual()) {
            return parseNumber(value.asText());
        }
        throw new IllegalArgumentException("missing numeric field: " + fieldName);
    }

    private double parseNumber(String value) {
        Matcher matcher = NUMBER_PREFIX_PATTERN.matcher(value);
        if (!matcher.find()) {
            throw new IllegalArgumentException("invalid number: " + value);
        }
        return Double.parseDouble(matcher.group());
    }

    private void validateRequest(SensorDataRequest request) {
        if (request == null) {
            throw new IllegalArgumentException("request is null");
        }
        if (request.getTemperature() == null || request.getHumidity() == null || request.getGas() == null) {
            throw new IllegalArgumentException("temperature, humidity and gas are required");
        }
    }

    private int boundLimit(int limit) {
        return Math.max(1, Math.min(limit, 500));
    }

    private double round1(double value) {
        return Math.round(value * 10.0) / 10.0;
    }
}
